### ISSUE TITLE
상품 단건 조회 시, 일부 상품들이 프론트 화면에 표시안되는 오류 발생

### ISSUE THREAD

**Issue by kjungw1025** [SWM-WeLike2Coding/ELSwhere-mobile#59]
상품 단건 조회 시, 일부 상품들이 프론트 화면에 표시안되는 오류 발생했습니다.
단건 조회 API 호출 후, 값을 받아서 처리하는 과정에 있는 문제 같습니다!

**Comment by popopy0412** [comment]
해결했습니다~!
